name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Alibaba Cloud Container Registry
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin registry.cn-shenzhen.aliyuncs.com

      - name: Build Docker image
        run: docker build -t registry.cn-shenzhen.aliyuncs.com/diflow/diflow:latest .

      - name: Push Docker image
        run: docker push registry.cn-shenzhen.aliyuncs.com/diflow/diflow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Debug SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          ssh-keygen -l -f ~/.ssh/private_key || echo "Invalid key format"
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 登录阿里云 Docker registry
            docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password ${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com

            # 拉取最新的 Docker 镜像
            docker pull registry.cn-shenzhen.aliyuncs.com/diflow/diflow:latest

            # 停止并删除已经存在的名为 diflow-server 的容器（如果有）
            docker ps -q --filter "name=diflow-server" | grep -q . && docker stop diflow-server || echo "Container diflow-server is not running"
            docker ps -a -q --filter "name=diflow-server" | grep -q . && docker rm diflow-server || echo "Container diflow-server does not exist"

            # 检查端口 3001 是否被占用，如果被占用，停止并删除相关容器
            docker ps -q --filter "publish=3001" | grep -q . && \
              docker ps -q --filter "publish=3001" | xargs -I {} docker stop {} && \
              docker ps -a -q --filter "publish=3001" | xargs -I {} docker rm {} || echo "Port 3001 is not occupied"

            # 启动 Docker Compose 
            docker-compose down # 确保旧容器被停止并删除
            docker-compose up -d --build # 使用 Docker Compose 启动新容器

            # 运行新容器并挂载卷
            docker run -d --name diflow-server -p 3001:3001 -v /www/wwwroot/blog.junfeng530.xyz/uploads:/www/wwwroot/blog.junfeng530.xyz/uploads registry.cn-shenzhen.aliyuncs.com/diflow/diflow:latest
